spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.11.56:9092
        bindings:
          send-mail-in:
            group-id: send-mail-group
            consumer:
              requeue-rejected: true
              autoCommitOffset: false   # 위치가 여기임을 주의..
              max:
                poll:
                  interval:
                    ms: 60000

      bindings:
        greeting-in:
          destination: greetings
          contentType: application/json
        greeting-out:
          destination: greetings
          contentType: application/json

        send-mail-in:
          group-id: send-mail-group
          destination: send-mail
          contentType: application/json
          consumer:
            max-attempts: 1             #spring retry의 retry template 인자를 위한 count
        send-mail-out:
          group-id: send-mail-group
          destination: send-mail
          contentType: application/json


  kafka:
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: manual


